name: t1
description: A simple login demo application using Flutter.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependências adicionais podem ser adicionadas aqui, se necessário

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
